[build]
builder = "NIXPACKS"
buildCommand = "npm install"
watchPatterns = ["backend/"]
rootDirectory = "backend"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
multiRegionConfig = { "asia-southeast1-eqsg3a" = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
