[build]
builder = "NIXPACKS"
buildCommand = "npm install"
watchPatterns = ["backend/"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig."asia-southeast1-eqsg3a"]
numReplicas = 1
